name: auto-sync

on:
  schedule:
    - cron: "0 19 * * *"

  workflow_dispatch:

jobs:
  auto-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"

      - run: |
          mkdir -p tmp/
          > tmp/urls.txt
          echo https://www.socpk.com/cpucurve/ >> tmp/urls.txt
          echo https://www.socpk.com/cpucurve/gb6/ >> tmp/urls.txt
          echo https://www.socpk.com/gpucurve/ >> tmp/urls.txt
          echo https://www.socpk.com/laptopgpucurve/ >> tmp/urls.txt
          echo https://www.socpk.com/game/ >> tmp/urls.txt
          echo https://www.socpk.com/allperf/ >> tmp/urls.txt
          echo https://www.socpk.com/cpu/ >> tmp/urls.txt
          echo https://www.socpk.com/gpu/ >> tmp/urls.txt
          echo https://www.socpk.com/cpueffcrank/ >> tmp/urls.txt
          echo https://www.socpk.com/geekbench6/ >> tmp/urls.txt
          echo https://www.socpk.com/geekbench5/ >> tmp/urls.txt
          echo https://www.socpk.com/gfx/ >> tmp/urls.txt
          echo https://www.socpk.com/3dmwle/ >> tmp/urls.txt
          echo https://www.socpk.com/log/ >> tmp/urls.txt
          echo https://www.socpk.com/batlife/ >> tmp/urls.txt
          wget --content-disposition --restrict-file-names=windows --adjust-extension --convert-links --page-requisites --no-parent --reject "*.ttf" --no-host-directories --input-file=tmp/urls.txt --tries=3 --connect-timeout=30 --verbose || true
          rm -rf tmp/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            echo "$(git diff --cached)"
            git commit -m "auto sync"
            git push origin main
          fi
